RDKCOM-3464: REFPLTB-1901 RPI 4 64 Bit Compilation Error in CCSP Misc
build errors in CcspMisc while building RPi4 Broadband 64bit:
| CcspMisc/source/dhcp_client_utils/dhcp_client_common.c:265:35: error: format '%lld' expects argument of type 'long long int', but argument 7 has type 'int64_t' {aka 'long int'} [-Werror=format=]
|   265 |                         DBG_PRINT(%s %d: %s running in pid %lld.. checking for cmdline param %s\n, __FUNCTION__, __LINE__, name, pid, args);
|       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                ~~~
|       |                                                                                                                                    |
|       |                                                                                                                                    int64_t {aka long int}
| CcspMisc/source/dhcp_client_utils/dhcp_client_utils.h:64:53: note: in definition of macro 'DBG_PRINT'
|    64 |         RDK_LOG(RDK_LOG_INFO, LOG.RDK.WANMANAGER, fmt, ##arg);
|       |                                                     ^~~
| CcspMisc/source/dhcp_client_utils/dhcp_client_common.c:265:64: note: format string is defined here
|   265 |                         DBG_PRINT(%s %d: %s running in pid %lld.. checking for cmdline param %s\n, __FUNCTION__, __LINE__, name, pid, args);
|       |                                                             ~~~^
|       |                                                                |
|       |                                                                long long int
|       |                                                             %ld
| CcspMisc/source/dhcp_client_utils/dhcp_client_common.c:266:72: error: format '%lld' expects argument of type 'long long int', but argument 4 has type 'int64_t' {aka 'long int'} [-Werror=format=]
|   266 |                         snprintf(filename, sizeof(filename), /proc/%lld/cmdline, pid);
|       |                                                                     ~~~^           ~~~
|       |                                                                        |           |
|       |                                                                        |           int64_t {aka long int}
|       |                                                                        long long int
|       |                                                                     %ld

Reason for change: REFPLTB-1901 RPI 4 64 Bit Compilation Error in CCSP Misc
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen_barrett@comcast.com>

(cherry picked from commit 61a1c6971b20389804393d133d17df265bf73e1d)
Change-Id: I2f89cb2367f2c556c26e9f30cd40da8c45de31e8